### ISSUE TITLE
rust_swig does not work with swig itself

### ISSUE THREAD

**Issue by yjiangnan** [Dushistov/rust_swig#199]
My plan was to use rust_swig to generate some C++ code for Rust structs and methods, and then use swig to wrap it into all other languages. However, the C++ code generated by rust_swig cannot compile within swig wrapper code and I got a bunch of errors (for python):
```
/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c qtwinclient_wrap.cpp -o build/temp.macosx-10.6-intel-3.6/qtwinclient_wrap.o -mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++
qtwinclient_wrap.cpp:3057:39: error: call to deleted constructor of 'rust::QtWinClientWrapper<false>'
  ...= SWIG_NewPointerObj((new rust::QtWinClientWrapper< false >(static_cast< const rust::QtWinClientWrapper< false >& >(result))), SWIG...
                               ^                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
qtwinclient_wrap.cpp:1096:89: note: expanded from macro 'SWIG_NewPointerObj'
#define SWIG_NewPointerObj(ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
                                                                                        ^~~
./../c++/rust_interface/QtWinClient.hpp:53:5: note: 'QtWinClientWrapper' has been explicitly marked deleted here
    QtWinClientWrapper(const QtWinClientWrapper&) = delete;
    ^
qtwinclient_wrap.cpp:3153:14: error: call to deleted constructor of 'rust::RustString'
  RustString result;
             ^
./../c++/rust_interface/rust_str.h:54:5: note: 'RustString' has been explicitly marked deleted here
    RustString() = delete;
    ^
qtwinclient_wrap.cpp:32:69: error: call to deleted constructor of 'rust::QtWinClientWrapper<false>'
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
                                                                    ^ ~
qtwinclient_wrap.cpp:3056:10: note: in instantiation of member function 'SwigValueWrapper<rust::QtWinClientWrapper<false> >::operator='
      requested here
  result = ((rust::QtWinClientWrapper< true > const *)arg1)->as_rref();
         ^
./../c++/rust_interface/QtWinClient.hpp:53:5: note: 'QtWinClientWrapper' has been explicitly marked deleted here
    QtWinClientWrapper(const QtWinClientWrapper&) = delete;
    ^
3 errors generated.
error: command '/usr/bin/clang' failed with exit status 1
```
The swig `.i` file I have is:
```%module qtwinclient
%{
    #include "../c++/rust_interface/rust_str.h"
    #include "../c++/rust_interface/QtWinClient.hpp"
    using namespace rust;
%}

%include "c++/rust_interface/QtWinClient.hpp"
namespace rust{
    %template(QtWinClient) QtWinClientWrapper<true>;
}
```
The swig command for generating the wrapper code is:
```
swig -python -c++  -o python/qtwinclient_wrap.cpp qtwinclient.i
```
Maybe I have done something inappropriate, but the files generated by rust_swig seems too complicated for me to judge. 

By the way, the following assertion could not pass and I have commented it out:
```
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversation usize <-> uintptr_t is wrong");
```
However, when I run `cout<<sizeof(uintptr_t) << " "<< sizeof(uint8_t)<<endl;` in Xcode, the output was `8 1`.  This seems strange.

The original Rust code to wrap is:
```
extern crate reqwest;
use reqwest::Client;

#[derive(Debug)]
pub struct QtWinClient {
    session: Client
}


impl QtWinClient {
    pub fn new() -> QtWinClient {
        return QtWinClient{session: reqwest::Client::new()};
    }
    
    pub fn get(&self, url: &str) -> String{
        let mut resp = self.session.get(url).send().unwrap();
        resp.text().unwrap()
    }
}
```
And the glue code for rust_swig is:
```
extern crate qtwinclient;

use qtwinclient::QtWinClient;

foreigner_class!(class QtWinClient {
    self_type QtWinClient;
    constructor QtWinClient::new() -> QtWinClient;
    method QtWinClient::get(&self, url: &str) -> String;
});
```
I really hope rust_swig can be tested with swig. swig is already mature and support many languages and in most cases it is not necessary to re-invent the wheel. 
```
$ swig -version

SWIG Version 4.0.0

Compiled with g++ [x86_64-apple-darwin16.5.0]

Configured options: +pcre
```

**Comment by Dushistov** [comment]
> However, the C++ code generated by rust_swig cannot compile within swig wrapper code and I got a 
> bunch of errors (for python):

This is not the problem of `rust_swig`. By default `rust_swig` generates move only C++ classes. And looks like `swig` can not handle such classes: https://github.com/swig/swig/issues/999

You can instruct rust_swig to generate copy constructor/assignment operator=,
but QtWinClient should implemnt `Clone trait`:

```
foreigner_class!(
#[derive(Copy)]
class QtWinClient {
    self_type QtWinClient;
    constructor QtWinClient::new() -> QtWinClient;
    method QtWinClient::get(&self, url: &str) -> String;
    method QtWinClient::clone(&self) -> QtWinClient;
});
```

it is also possible to use `Rc<RefCell` and `Arc<Mutex` for holding pointer,
but I never test `Rc<RefCell` + Copy.

> By the way, the following assertion could not pass and I have commented it out:

I suppose you code crashes if you run it. In the most cases this assert means that you compile rust part as 64 bit, and you try to use it from 32bit C++ code.

**Comment by yjiangnan** [comment]
I know swig have difficulties dealing with moving objects. However, there is often workaround in my experience, such as hiding those objects from swig. 

The static_assert error seems to be result from my `setup.py` by default using compiling flags `-arch i386 -arch x86_64` together. It compiles when I remove `-arch i386`. 

However, RustString still cause errors due to deleted constructor. I workaround it by changing the return type from String to &str pointing to an added String field in the struct. 

I also get errors due to assert `static_assert(OWN_DATA, "copy possible only if class own data")`. I work around it by commenting out all lines with `QtWinClientWrapper<false>` (I am not sure why it is necessary to put both true and false in the same file; maybe allowing configuring it or output into different files will be helpful). Now everything is successfully built for Python. The only problem I get is that when importing the module, I get an error:
```
>>> import qtwinclient as qw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtwinclient/__init__.py", line 1, in <module>
    from .qtwinclient import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtwinclient/qtwinclient.py", line 74, in <module>
    class QtWinClient(_object):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtwinclient/qtwinclient.py", line 99, in QtWinClient
    __swig_destroy__ = _qtwinclient.delete_QtWinClient
AttributeError: module 'qtwinclient._qtwinclient' has no attribute 'delete_QtWinClient'
```
I am not sure where and how to add this missing function `delete_QtWinClient`. Since I have come this long with this path, I still believe that it is possible to work through this pipeline of Rust -> rust_swig -> C++ -> swig -> many other languages. Testing rust_swig with swig in mind would be fruitful.

**Comment by Dushistov** [comment]
@yjiangnan 

On my side all works in right way (Linux/swig 4.0/python 3.7.3), but I simplified your example, see attachment with full example:

```sh
cd c++/rust_interface
swig -python -c++  -o qtwinclient_wrap.cpp test.i
cp -i ../../target/debug/librust_swig_test.a ./
g++ -fPIC -I/usr/include/python3.7m qtwinclient_wrap.cpp librust_swig_test.a -shared -o _test.so
$ python
Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import test
>>> a = test.QtWinClient()
>>> a.get("test me you can://")
hello from rust, url test me you can://
17
>>> 
```

[c++_tests.zip](https://github.com/Dushistov/rust_swig/files/3218717/c%2B%2B_tests.zip)

**Comment by yjiangnan** [comment]
@Dushistov 
It could be a compiler issue here. I follow your example but I cannot compile. My compiler is 
```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
```
The operation system is Mac OS X Sierra 10.12.4.

I get a long list of errors such as
```
./QtWinClient.hpp:30:43: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    QtWinClientWrapper(QtWinClientWrapper &&o) noexcept: self_(o.self_)
                                          ^
./QtWinClient.hpp:30:47: error: expected ';' at end of declaration list
    QtWinClientWrapper(QtWinClientWrapper &&o) noexcept: self_(o.self_)
                                              ^
                                              ;
./QtWinClient.hpp:85:30: error: expected ';' at end of declaration list
    QtWinClient clone() const  noexcept;
                             ^
                             ;
./QtWinClient.hpp:88:37: error: expected ';' at end of declaration list
   static void free_mem(SelfType &p) noexcept
                                    ^
                                    ;
./QtWinClient.hpp:108:50: error: out-of-line declaration of 'get' does not match any declaration in 'QtWinClientWrapper<>'
    inline int32_t QtWinClientWrapper<OWN_DATA>::get(const char * a_0) const  noexcept
                                                 ^~~
./QtWinClient.hpp:108:77: error: expected ';' at end of declaration
    inline int32_t QtWinClientWrapper<OWN_DATA>::get(const char * a_0) const  noexcept
                                                                            ^
                                                                            ;
./QtWinClient.hpp:108:79: error: C++ requires a type specifier for all declarations
    inline int32_t QtWinClientWrapper<OWN_DATA>::get(const char * a_0) const  noexcept
                                                                              ^
./QtWinClient.hpp:108:87: error: expected ';' after top level declarator
    inline int32_t QtWinClientWrapper<OWN_DATA>::get(const char * a_0) const  noexcept
```
When I compile by adding `-std=c++11`, the error message is simpler:
```
jiangnan$ clang -fPIC qtwinclient_wrap.cpp librust_swig_test.a -shared -o _test.so -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -std=c++11
In file included from qtwinclient_wrap.cpp:2831:
./QtWinClient.hpp:54:17: error: static_assert failed "copy possible only if class own data"
                static_assert(OWN_DATA, "copy possible only if class own data");
                ^             ~~~~~~~~
qtwinclient_wrap.cpp:3073:39: note: in instantiation of member function 'rust::QtWinClientWrapper<false>::QtWinClientWrapper' requested here
  resultobj = SWIG_NewPointerObj((new rust::QtWinClientWrapper< false >(static_cast< const rust::QtWinClientWrapper< false >& >(result))), SWIGTYPE_p_rust__QtWinCl...
```
It seems that your are using C++17 standard. Is it necessary to use C++17? I will have to upgrade my whole operation system to use C++17. For a library, it may be better to support older versions of C++.

**Comment by Dushistov** [comment]
> It could be a compiler issue here
> I get a long list of errors such as

By default g++ 8.x uses c++14 standard,
on other platforms/compiler you need another switches.

> When I compile by adding -std=c++11, the error message is simpler:

if you look at archive I modified generated code and removed such line manually from generated code: 

```C++
QtWinClientWrapper<false> as_rref() const noexcept { return QtWinClientWrapper<false>{ self_ }; }
```

> It seems that your are using C++17 standard. Is it necessary to use C++17?

No and no. I use default gcc's standard - C++14, 
but I repeated the same steps, but with `-std=c++11` all works fine on my side.

> For a library, it may be better to support older versions of C++.

It is just copy/paste from c++_tests, which is used to test various things including compilation with 
 and without c++17, all generated by rust_swig code is c++11 is compatible, 
until you explicitly specify that you want to use c++17 stuff (std::variant/std::optional)

**Comment by yjiangnan** [comment]
@Dushistov 
Then what do you think is the problem? Is it because of the compiler? I am using clang not g++. 

Nevertheless, I am able to get your example to work, on condition that I delete the three lines with `QtWinClientWrapper<false>` in file `QtWinClient.hpp` and compile by adding ` -std=c++11 -undefined dynamic_lookup`:
```
clang -fPIC -shared qtwinclient_wrap.cpp librust_swig_test.a -o _test.so `python3-config --includes` -std=c++11 -undefined dynamic_lookup
```
 However, things start to fail again as soon as I add `extern crate reqwest;` to the beginning of file `src/lib.rs` (and add `[dependencies]` section with `reqwest = "*"` in `Cargo.toml`. The compile was successful. But when I import it in Python, I get errors:
```
jiangnan$ python3
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import test
Traceback (most recent call last):
  File "/Users/jiangnan/Documents/software/workspace/qtwinclient/c++tests/c++/rust_interface/test.py", line 15, in swig_import_helper
    return importlib.import_module(mname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: dlopen(/Users/jiangnan/Documents/software/workspace/qtwinclient/c++tests/c++/rust_interface/_test.so, 2): Symbol not found: _kSecAttrKeyType
  Referenced from: /Users/jiangnan/Documents/software/workspace/qtwinclient/c++tests/c++/rust_interface/_test.so
  Expected in: flat namespace
 in /Users/jiangnan/Documents/software/workspace/qtwinclient/c++tests/c++/rust_interface/_test.so
```
This seems very strange to me. My understanding is that everything is Rust is hidden from outside except for the APIs specified in rust_swig. Then, how does specifying an extern crate in Rust create errors in Python??

**Comment by Dushistov** [comment]
>  My understanding is that everything is Rust is hidden from outside except for the APIs specified in rust_swig
> Then, how does specifying an extern crate in Rust create errors in Python??

This is how compiler/linkers works, this is not related to rust_swig.
In my example I used the same technique as in c++_tests,
in other words, you can find in Cargo.toml such line
```toml
crate-type = ["staticlib"]
```
this means that cargo/rustc produces as final result `.a` library on Linux/Mac OS X.
`.a` library is just archive with of object files, no information about external dependencies.

To deals with it, in c++_tests there is `c++/cmake/rust_cargo.cmake` file that calls
`rustc --crate-type staticlib  --print=native-static-libs`, so after linking with `main.cpp` there is no symbol undefined error.

But this magic works only for crate without deps, you use `reqwest` by default it uses openssl on Linux and "Secure Transport" framework on Mac OS X.
You should tells `clang` to link with    "Secure Transport".
The another way to deals with it is usage of `crate-type = ["cdylib"]`, then resulted `.so` would contain all information about dependencies and there is no need to specify it by hands,
but there is no way to link qtwinclient_wrap.cpp with `.so`, 
so you should use `build.rs` to generate and link qtwinclient_wrap.cpp into resulted shared library.

Or you can use rust only solution for SSL:
```toml
reqwest = { version = "0.9.17", default-features = false, features=["rustls-tls"] }
```
but for some reason this configuration marked as dangerous.

**Comment by yjiangnan** [comment]
@Dushistov 
Actually, compiling to `cdylib` solved the problem on my side and the process is not as complicated as you described. 
The command I have is
```
grep -v 'QtWinClientWrapper<false>' QtWinClient.hpp > QtWinClient.h
swig -python -c++ -o qtwinclient_wrap.cpp test.i
cp ../../target/debug/librust_swig_test.dylib .
clang -fPIC -shared qtwinclient_wrap.cpp -o _test.so `python3-config --includes` -std=c++11 -undefined dynamic_lookup -L. -lrust_swig_test
```
Then everything just works. However, I still cannot get `String` as return to work. If I just return `String`, then I get compiling error:
```
qtwinclient_wrap.cpp:3175:14: error: call to deleted constructor of 'rust::RustString'
  RustString result;
             ^
./rust_str.h:54:5: note: 'RustString' has been explicitly marked deleted here
    RustString() = delete;
```
So, I have to return `&str` and then it compiles. But running python, I get memory leaks:
```
jiangnan$ python3
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import test
>>> t = test.QtWinClient()
>>> t.get('aa')
<Swig Object of type 'RustStrView *' at 0x10188ba20>
>>> t.get('aa')
swig/python detected a memory leak of type 'RustStrView *', no destructor found.
<Swig Object of type 'RustStrView *' at 0x10188bba0>
```
Additionally, there is no way to get what is inside RustStrView. This is apparently because I did not wrap `rust_str.h`. However, I if I add it into `test.i` as:
```
%module test
%{
    #include "rust_str.h"
    #include "QtWinClient.h"
    using namespace rust;
%}
%include "std_string.i"
%include "rust_str.h"
%include "QtWinClient.h"
namespace rust{
    %template(QtWinClient) QtWinClientWrapper<true>;
}
```
I get a single-line errors `rust_str.h:46: Error: Syntax error in input(1).` when running `swig`.

By the way, `lib.rs` now looks like:
```
extern crate reqwest;
mod cpp_glue;
pub use crate::cpp_glue::*;

#[derive(Debug, Clone)]
pub struct QtWinClient {
    buffer: String
}

impl QtWinClient {
    pub fn new() -> QtWinClient {
        return QtWinClient{buffer: String::new()};
    }
    pub fn get(&mut self, url: &str) -> &str{
        self.buffer = format!("url is {}. ", url);
        &self.buffer
    }
}
```

**Comment by Dushistov** [comment]
> But running python, I get memory leaks:

This is how swig (not **rust_swig**) works, if it encounters unknown type it wrap it with pointer and new,
so you get memory leak.

> I get a single-line errors rust_str.h:46: Error: Syntax error in input(1).

Looks like bug in swig, it not handle **final** keyword in such context `class Derive final : Base`.

I've added copy constructor/assigment operator to `RustString`,
so with current master  all works for me, plus I modified your _test.i_ so there is no
need of any modification in generated by rust_swig files (`as_rref`):

```
%module test

%include "stdint.i"
%include "std_string.i"

%{
    #include "rust_str.h"
    #include "QtWinClient.hpp"
    using namespace rust;
%}

#define final /**/

%include "rust_str.h"
%ignore as_rref;
%include "QtWinClient.hpp"
namespace rust{
    %template(QtWinClient) QtWinClientWrapper<true>;
}
```

```sh
cargo build
cp -i ../../target/debug/librust_swig_test.a ./
swig  -python -c++  -o qtwinclient_wrap.cpp test.i 
g++ -std=c++11 -fPIC -I/usr/include/python3.7m qtwinclient_wrap.cpp librust_swig_test.a -shared -o _test.so
```

```Python
Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import  test
>>> t = test.QtWinClient()
>>> t.get('aa')
<test.RustString; proxy of <Swig Object of type 'rust::RustString *' at 0x7f8c73d58e70> >
>>> t.get('aa')
<test.RustString; proxy of <Swig Object of type 'rust::RustString *' at 0x7f8c73d58e40> >
>>> s = t.get('aa')
>>> s.to_std_string()
'hello from rust, url aa'
>>> 
```

**Comment by wsfulton** [comment]
The original compilation errors reported here are now fixed in SWIG, see https://github.com/swig/swig/issues/1044.
